stages:
  - build
  - test

variables:
  GO_VERSION: "1.21"

before_script:
  - apt-get update -y && apt-get install -y git
  - go version

build:
  stage: build
  script:
    - go build ./cmd/...

unit_test:
  stage: test
  script:
    - go test ./... 